### ISSUE TITLE
Issue with filter method for subsetting daFrame

### ISSUE THREAD

**Issue by biskra** [HelenaLC/CATALYST#50] opened 2019-07-07 03:41 UTC
Hi,

I am trying to subset the clusters in my data and remove a specific cluster. To do this, I am calling:

`CATALYST::filter(daf, cluster_ids(daf) != 20, k = 'meta20')`

The daFrame returned contains the same number of cells as the original and the rowData names is zeroed.

Original daFrame

`class: daFrame 
dim: 907320 18 
metadata(5): experiment_info cofactor SOM_codes cluster_codes delta_area
assays(1): exprs
rownames: NULL
rowData names(3): sample_id condition cluster_id
colnames(18): CD45 TNFa ... CD200 IAIE
colData names(3): channel_name marker_name marker_class
reducedDimNames(1): UMAP
spikeNames(0):`

After filtering:

`class: daFrame 
dim: 907320 18 
metadata(5): experiment_info cofactor SOM_codes cluster_codes delta_area
assays(1): exprs
rownames: NULL
rowData names(0):
colnames(18): CD45 TNFa ... CD200 IAIE
colData names(3): channel_name marker_name marker_class
reducedDimNames(0):
spikeNames(0):`

Is this working as intended? 

Thanks!

**Comment by dhuvik** [comment] 2019-07-30 20:15
Hi I am having the same issue as the above and it doesn't let me generate any of the plots that for use in downstream analysis. Anyone encounter something similar and can suggest a fix?

**Comment by dhuvik** [comment] 2019-08-16 00:43
It seems the issue is coming from the last step in the filter function where the filtering has been done as a Summarized Experiment and R is having some difficulty converting the Summarized Experiment back to a daFrame. Hope this helps!

**Comment by HelenaLC** [comment] 2019-11-07 07:47
Apologies for the (very very) late response... As you may  have noticed, Bioc 3.10 was released recently. With that, there have been many updates (hopefully improvements) to `CATALYST`. Most significantly, the `daFrame` class was replaced by a classical `SingleCellExperiment` to simplify interaction with Bioc infrastructure. I believe the filtering is now working and will close the issue. Of course, feel free to re-open it should it persist!

**Closed by HelenaLC** 2019-11-07 07:47 UTC
