### ISSUE TITLE
prepData error

### ISSUE THREAD

**Issue by Hezh123** [HelenaLC/CATALYST#133] opened 2020-08-25 01:11 UTC
Hi! When I convert the flowframe to SingleCellExperiment object, always an error happens, 
![image](https://user-images.githubusercontent.com/69892579/91111346-e512c080-e6b2-11ea-9ca5-4c2797724e43.png)I am already fighting with this for a week! Thank you guys!

**Comment by HelenaLC** [comment] 2020-08-25 04:37
This is a duplicate of issue #125

**Closed by HelenaLC** 2020-08-25 04:37 UTC
