### ISSUE TITLE
Loss of channels in the SingleCellExperiment with the unction prepData

### ISSUE THREAD

**Issue by PaulineMaby** [HelenaLC/CATALYST#150] opened 2020-10-09 14:49 UTC
The fcs files that I imported in the flowset (with the fuction fs <- read.flowSet(path= original.file.folder, transformation=FALSE, truncate_max_range = FALSE)),  contain 36 marker channels (CD3, CD4…) and a channel named « cluster » that is a spade cluster that I would lke to keep for the UMAP visualisation.
This « cluster »  channel is kept in the fs, as shown by:

fs@frames[["03n2.fcs"]]@description[["$P39S"]]
 $*P395       character (1)         ‘cluster’

This « cluster »  channel is in the panel.xslx file that I used to create a SingleCellExperiment with the fonction sce <- prepData(fs, panel, md, features = panel$fcs_colname)

 However, even if this « cluster »  channel is present within features = panel$fcs_colname,  when I create a SingleCellExperiment from this fs (with prepData), only the 36 marker channels are kept and the « cluster »  channel is lost, as shown by:

scetest@int_elementMetadata@rownames
nrows    integer(1)    36

I wonder how to avoid this channel loss, in order to be able to map some of the spade clusters on the UMAP plot ?

**Comment by HelenaLC** [comment] 2020-10-09 15:00
duplicate of #151

**Closed by HelenaLC** 2020-10-09 15:00 UTC
