### ISSUE TITLE
Code to get value of cell abundance without plot

### ISSUE THREAD

**Issue by YukawaS** [HelenaLC/CATALYST#277] opened 2022-04-29 14:27 UTC
I would like to save value of cell abundance for each cell population in each patient to csv file.
I only knew 'plotAbundance()' calculates cell abundance on the way to create plot, but plotAbudance() couldn't be saved to csv file because it's plot. 
Is there any way to save value of cell abundance to csv file?

**Comment by HelenaLC** [comment] 2022-04-30 08:04
duplicate of #183 and #222

**Closed by HelenaLC** 2022-04-30 08:04 UTC
