### ISSUE TITLE
CATALYST:::get_spill_cols(ms,mets) doesn't work

### ISSUE THREAD

**Issue by viniciusnmotta** [HelenaLC/CATALYST#198] opened 2021-04-13 09:50 UTC
Hi Helena,
I am trying to reproduce the script for figure 2,C: https://github.com/BodenmillerGroup/cyTOFcompensation
But the code CATALYST:::get_spill_cols(ms,mets) doesn't work.
Do I need to update CATALYST?  I am using version 1.10.1
Many thanks

**Comment by HelenaLC** [comment] 2021-04-13 11:18
Unfortunately, I fear updating the package won't solve this. The code to reproduce these figures was, at the time, fully functional and reproducible. However, the package has gone through significant development since then. The current equivalent function is `.get_spill_chs()`, but I think it's quite possible a few modifications would have to be made to get things running. Then again - I'm confident you could still reproduce the figure! I'm just not sure which parts of the code would need to be changed.

**Comment by viniciusnmotta** [comment] 2021-04-13 13:04
Hi Helena,

Thank you so much for your quick response.

I really like the scripts and workflow you made available. They are really
clear and easy to understand. Of course, the compensation algorithm is a
great tool. Do you always apply compensation to your mass cytometry data?

I think the problem is that I don't find neither functions (get_spill_chs
and get_spill_cols) definitions in your home page, to understand what it is
doing.

Where can I find the .get_spill_chs()?

Many thanks

Vinicius

**Comment by HelenaLC** [comment] 2021-04-13 13:54
In the current version of `CATALYST` - Bioc 3.12 release.

**Comment by viniciusnmotta** [comment] 2021-04-15 23:37
Hi Helena,

Thank you for your help.

I might be doing something wrong, but I have installed CATALYST from
Bioconductor and the function was not available as
CATALYST:::get_spills_chs() after the installation

However, I was able to find the method here (
https://github.com/HelenaLC/CATALYST/blob/master/R/utils-compensation.R)
and copy it into Rstudio and is working fine.

Would you know why it isn't available within the CATALYST package? I am
learning R sorry for the basic question.

Many thanks

Vinicius

**Comment by HelenaLC** [comment] 2021-04-16 06:16
The three ::: give access to internal functions, ie ones that are not exported

i think you are missing a dot? I changed my style a few years back to make self-written helper functions with a . in front to distinguish them from other functions.

**Comment by HelenaLC** [comment] 2021-05-31 08:39
Closing due to unresponsiveness - feel free to re-open should the issue persist.

**Closed by HelenaLC** 2021-05-31 08:39 UTC
